{
 "title": "Corona Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "country", "query": "label_values(country)" }
  ]
 },
 "panels": [
  {
   "title": "Recovered People",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "People" }
   ],
   "targets": [
    {
     "expr": "total_recovered_corona_in_country{country=\"$country\"}"
    }
   ]
  },
  {
   "title": "Confirmed Corona",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "People" }
   ],
   "targets": [
    {
     "expr": "total_confirmed_corona_in_country{country=\"$country\"}"
    }
   ]
  },
  {
   "title": "Case Fatality Corona",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "People" }
   ],
   "targets": [
    {
     "expr": "total_death_corona_in_country{country=\"$country\"}"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 8 },
   "targets": [
    {
     "expr": "death_rate_corona_in_country{country=\"$country\"}"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "recovery_rate_corona_in_country{country=\"$country\"}"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "100-death_rate_corona_in_country{country=\"$country\"}-recovery_rate_corona_in_country{country=\"$country\"}"
    }
   ]
  }
 ]
}